[package]
name = "gdk4-wayland"
version = "0.1.0"
authors = ["Bilal Elmoussaoui <bil.elmoussaoui@gmail.com>"]
edition = "2018"

[dependencies]
libc = "0.2"
wayland-client = { version = "0.28", features = ["use_system_lib"] }

[dependencies.glib]
git = "https://github.com/gtk-rs/gtk-rs"

[dependencies.glib_sys]
git = "https://github.com/gtk-rs/gtk-rs"
package = "glib-sys"

[dependencies.gio]
git = "https://github.com/gtk-rs/gtk-rs"

[dependencies.gobject_sys]
git = "https://github.com/gtk-rs/gtk-rs"
package = "gobject-sys"

[dependencies.gdk]
path = "../gdk4"
package = "gdk4"

[dependencies.ffi]
path = "./sys"
package = "gdk4-wayland-sys"