[options]
girs_dir = "gir-files"
library = "Gsk"
version = "4.0"
min_cfg_version = "3.94"
target_path = "."
work_mode = "normal"
generate_safety_asserts = true
single_version_file = true
deprecate_by_min_version = true

generate = [
    "Gsk.BlendMode",
    "Gsk.BroadwayRenderer",
    "Gsk.CairoRenderer",
    "Gsk.Corner",
    "Gsk.GLRenderer",
    "Gsk.RenderNodeType",
    "Gsk.Renderer",
    "Gsk.ScalingFilter",
    "Gsk.SerializationError",
    "Gsk.Transform",
    "Gsk.TransformCategory",
    "Gsk.VulkanRenderer",
]

manual = [
    "cairo.Context",
    "cairo.Region",
    "cairo.Surface",
    "Gdk.RGBA",
    "Gdk.Surface",
    "Gdk.Texture",
    "GLib.Bytes",
    "GLib.Error",
    "GLib.String",
    "Graphene.Matrix",
    "Graphene.Point",
    "Graphene.Point3D",
    "Graphene.Rect",
    "Graphene.Vec3",
    "Graphene.Vec4",
    "Pango.Font",
    # "Pango.GlyphInfo", # missing from pango
    "Pango.GlyphString",
]

ignore = [
    "Gsk.ColorStop", # Missing memory management functions
    "Gsk.RoundedRect", # Missing memory management functions
    "Gsk.Shadow", # Missing memory management functions
]

[[object]]
name = "Gsk.*"
status = "generate"
    [[object.function]]
    # gir error
    name = "border_node_peek_widths"
    ignore = true
    [[object.function]]
    # binding generation error
    name = "container_node_new"
    ignore = true
    [[object.function]]
    name = "cairo_node_peek_surface"
    ignore = true # no impl FromGlibPtrNone<*const cairo_surface_t> for Surface, probably by mistake

[[object]]
name = "Gsk.RenderNode"
status = "generate"
    [[object.function]]
    name = "draw"
        [[object.function.parameter]]
            name = "cr"
            const = true
