[options]
girs_dir = "gir-files"
library = "Gdk"
version = "4.0"
min_cfg_version = "3.94"
target_path = "."
work_mode = "normal"
generate_safety_asserts = true
single_version_file = true
deprecate_by_min_version = true

generate = [
    "Gdk.AnchorHints",
    "Gdk.AppLaunchContext",
    "Gdk.AxisFlags",
    "Gdk.AxisUse",
    "Gdk.ByteOrder",
    "Gdk.CairoContext",
    "Gdk.Clipboard",
    "Gdk.ContentDeserializer",
    "Gdk.ContentFormatsBuilder",
    "Gdk.ContentProvider",
    "Gdk.ContentSerializer",
    "Gdk.CrossingMode",
    "Gdk.Cursor",
    "Gdk.DevicePad",
    "Gdk.DevicePadFeature",
    "Gdk.DeviceTool",
    "Gdk.DeviceToolType",
    "Gdk.DeviceType",
    "Gdk.Display",
    "Gdk.DisplayManager",
    "Gdk.Drag",
    "Gdk.DragAction",
    "Gdk.DragCancelReason",
    "Gdk.Drop",
    "Gdk.Event",
    "Gdk.EventMask",
    "Gdk.EventSequence",
    "Gdk.EventType",
    "Gdk.FrameClock",
    "Gdk.FrameClockPhase",
    "Gdk.FrameTimings",
    "Gdk.FullscreenMode",
    "Gdk.GLContext",
    "Gdk.GLError",
    "Gdk.GLTexture",
    "Gdk.GrabOwnership",
    "Gdk.GrabStatus",
    "Gdk.Gravity",
    "Gdk.InputMode",
    "Gdk.InputSource",
    "Gdk.MemoryFormat",
    "Gdk.MemoryTexture",
    "Gdk.ModifierIntent",
    "Gdk.ModifierType",
    "Gdk.Monitor",
    "Gdk.NotifyType",
    "Gdk.Paintable",
    "Gdk.PaintableFlags",
    "Gdk.ScrollDirection",
    "Gdk.Seat",
    "Gdk.SeatCapabilities",
    "Gdk.Snapshot",
    "Gdk.SubpixelLayout",
    "Gdk.SurfaceEdge",
    "Gdk.SurfaceHints",
    "Gdk.SurfaceState",
    "Gdk.SurfaceType",
    "Gdk.SurfaceTypeHint",
    "Gdk.Texture",
    "Gdk.TouchpadGesturePhase",
    "Gdk.VulkanContext",
    "Gdk.VulkanError",
    "Gdk.WMDecoration",
    "Gdk.WMFunction",
]

manual = [
    "cairo.Content",
    "cairo.Context",
    "cairo.Region",
    "cairo.Surface",
    "Gdk.Atom",
    "Gdk.Geometry",
    "Gdk.KeymapKey",
    "Gdk.RGBA",
    "Gdk.TimeCoord",
    "GdkPixbuf.Pixbuf",
    "Gio.Cancellable",
    "Gio.File",
    "Gio.Icon",
    "Gio.OutputStream",
    "GLib.Bytes",
    "GLib.Error",
    "GLib.Priority",
    "GLib.String",
    "GObject.Value",
    "Pango.Direction",
    "Pango.Layout",
    "Pango.LayoutLine",
]

[[object]]
name = "Gdk.*"
status = "generate"
    [[object.function]]
    pattern = ".+"
        [[object.function.parameter]]
        name = "cr"
        const = true
        [[object.function.parameter]]
        name = "surface"
        const = true
    [[object.function]]
    name = "pango_layout_get_clip_region"
    #manual
    ignore = true
    [[object.function]]
    name = "pango_layout_line_get_clip_region"
    #manual
    ignore = true

[[object]]
name = "Gdk.ContentFormats"
status = "generate"
    [[object.function]]
    # gir error
    name = "get_gtypes"
    ignore = true

[[object]]
name = "Gdk.Device"
status = "generate"
    [[object.function]]
    name = "get_history"
    # skip
    ignore = true
    [[object.function]]
    name = "free_history"
    # skip
    ignore = true

[[object]]
name = "Gdk.DrawContext"
status = "generate"
manual_traits = ["DrawContextExtManual"]
    [[object.function]]
    name = "get_frame_region"
    #manual
    ignore = true

[[object]]
name = "Gdk.Keymap"
status = "generate"
    [[object.function]]
    name = "add_virtual_modifiers"
    ignore = true
    [[object.function]]
    name = "get_entries_for_keycode"
    ignore = true #manual
    [[object.function]]
    name = "map_virtual_modifiers"
    ignore = true

[[object]]
name = "Gdk.Rectangle"
status = "generate"
init_function_expression = "|_ptr| ()"
clear_function_expression = "|_ptr| ()"

[[object]]
name = "Gdk.Surface"
status = "generate"
manual_traits = ["SurfaceExtManual"]
    [[object.function]]
    name = "create_similar_surface"
    #manual
    ignore = true
    [[object.function]]
    name = "set_opaque_region"
        [[object.function.parameter]]
        name = "region"
        const = true
