[options]
girs_dir = "gir-files"
library = "Gsk"
version = "4.0"
min_cfg_version = "3.94"
target_path = "."
work_mode = "normal"
generate_safety_asserts = true
single_version_file = true
deprecate_by_min_version = true

generate = [
    "Gsk.BlendMode",
    "Gsk.BlendNode",
    "Gsk.BlurNode",
    "Gsk.BroadwayRenderer",
    "Gsk.CairoNode",
    "Gsk.CairoRenderer",
    "Gsk.ClipNode",
    "Gsk.ColorMatrixNode",
    "Gsk.ColorNode",
    "Gsk.ContainerNode",
    "Gsk.Corner",
    "Gsk.CrossFadeNode",
    "Gsk.DebugNode",
    "Gsk.GLRenderer",
    "Gsk.InsetShadowNode",
    "Gsk.LinearGradientNode",
    "Gsk.OpacityNode",
    "Gsk.OutsetShadowNode",
    "Gsk.Renderer",
    "Gsk.RenderNodeType",
    "Gsk.RepeatingLinearGradientNode",
    "Gsk.RepeatNode",
    "Gsk.RoundedClipNode",
    "Gsk.ScalingFilter",
    "Gsk.SerializationError",
    "Gsk.ShadowNode",
    "Gsk.TextNode",
    "Gsk.TextureNode",
    "Gsk.Transform",
    "Gsk.TransformCategory",
    "Gsk.TransformNode",
    "Gsk.VulkanRenderer",
]

manual = [
    # "Gsk.ColorStop",
    # "Gsk.Shadow",
    # "Pango.GlyphInfo", # missing from pango
    "cairo.Context",
    "cairo.Region",
    "cairo.Surface",
    "Gdk.RGBA",
    "Gdk.Surface",
    "Gdk.Texture",
    "GLib.Bytes",
    "GLib.Error",
    "GLib.Quark",
    "GLib.String",
    "Graphene.Matrix",
    "Graphene.Point",
    "Graphene.Point3D",
    "Graphene.Rect",
    "Graphene.Size",
    "Graphene.Vec3",
    "Graphene.Vec4",
    "Gsk.RoundedRect",
    "Pango.Font",
    "Pango.GlyphString",
]

[[object]]
name = "Gsk.*"
status = "generate"

[[object]]
name = "Gsk.BorderNode"
status = "generate"
manual_traits = ["BorderNodeManualExt"]
    [[object.function]]
    name = "peek_widths"
    # manual
    ignore = true

[[object]]
name = "Gsk.RenderNode"
status = "generate"
    [[object.function]]
    name = "draw"
        [[object.function.parameter]]
            name = "cr"
            const = true
