[package]
name = "gdk4-x11"
version = "0.1.0"
authors = ["Bilal Elmoussaoui <bil.elmoussaoui@gmail.com>"]
edition = "2018"

[dependencies]
libc = "0.2"
x11 = "2.18"

[dependencies.glib]
git = "https://github.com/gtk-rs/gtk-rs"

[dependencies.glib_sys]
git = "https://github.com/gtk-rs/gtk-rs"
package = "glib-sys"

[dependencies.gio]
git = "https://github.com/gtk-rs/gtk-rs"

[dependencies.gobject_sys]
git = "https://github.com/gtk-rs/gtk-rs"
package = "gobject-sys"

[dependencies.gdk]
path = "../gdk4"
package = "gdk4"

[dependencies.gdk4_x11_sys]
path = "./sys"
package = "gdk4-x11-sys"
