[package]
documentation = "https://gtk-rs.org/docs/gtk4/"
categories = ["api-bindings", "gui"]
license = "MIT"
description = "Rust bindings for the GTK 4 library"
name = "gtk4"
homepage = "https://gtk-rs.org/"
authors = ["The Gtk-rs Project Developers"]
readme = "README.md"
version = "0.1.0"
keywords = ["gtk", "gtk4", "gtk-rs", "gnome", "GUI"]
repository = "https://github.com/gtk-rs/gtk4"
build = "build.rs"
edition = "2018"
exclude = [
    "gir-files/*",
]

[badges]
appveyor = { repository = "GuillaumeGomez/gtk4", service = "github" }
travis-ci = { repository = "gtk-rs/gtk4" }

[lib]
name = "gtk4"

[features]
purge-lgpl-docs = ["gtk-rs-lgpl-docs", "gdk4/purge-lgpl-docs", "gsk4/purge-lgpl-docs"]
embed-lgpl-docs = ["gtk-rs-lgpl-docs", "gdk4/embed-lgpl-docs", "gsk4/embed-lgpl-docs"]
dox = ["gdk4/dox", "gsk4/dox", "ffi/dox"]

[package.metadata.docs.rs]
features = ["dox", "embed-lgpl-docs"]

[build-dependencies.gtk-rs-lgpl-docs]
version = "0.1.3"
optional = true
git = "https://github.com/gtk-rs/lgpl-docs"

[dependencies]
libc = "0.2"
bitflags = "1.0"
once_cell = "1.0"
cairo-sys-rs = { git = "https://github.com/gtk-rs/gtk-rs" }
gdk-pixbuf-sys = { git = "https://github.com/gtk-rs/gtk-rs" }
gdk4-sys = { path = "../gdk4/sys" }
gio-sys = { git = "https://github.com/gtk-rs/gtk-rs" }
glib-sys = { git = "https://github.com/gtk-rs/gtk-rs" }
gobject-sys = { git = "https://github.com/gtk-rs/gtk-rs" }
graphene-sys = { git = "https://github.com/gtk-rs/gtk-rs" }
gsk4-sys = { path = "../gsk4/sys" }
ffi =  { package = "gtk4-sys", path = "./sys" }
pango-sys = { git = "https://github.com/gtk-rs/gtk-rs" }
cairo-rs = { git = "https://github.com/gtk-rs/gtk-rs" }
gio = { git = "https://github.com/gtk-rs/gtk-rs", features = ["v2_46"] }
glib = { git = "https://github.com/gtk-rs/gtk-rs" }
gdk4 = { path = "../gdk4" }
graphene = { package = "graphene-rs", git = "https://github.com/gtk-rs/gtk-rs" }
gsk4 = { path = "../gsk4" }
gdk-pixbuf = { git = "https://github.com/gtk-rs/gtk-rs" }
pango = { git = "https://github.com/gtk-rs/gtk-rs", features = ["v1_46"] }

[dev-dependencies]
gir-format-check = "^0.1"
