on:
  push:
    branches: [master]
  pull_request:

name: CI

jobs:
  check:
    name: Rust project
    runs-on: ubuntu-latest
    container:
      image: docker.io/bilelmoussaoui/gtk4
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - nightly
          - "1.40.0"
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true
      - name: install dependencies
        run: sudo dnf install -y xorg-x11-server-Xvfb
      # gsk4
      - name: "gsk4: tests"
        run: xvfb-run --auto-servernum cargo test --manifest-path gsk4/Cargo.toml --all-features
      - name: "gsk4: build"
        run: cargo build --manifest-path gsk4/Cargo.toml --all-features
      # gdk4
      - name: "gdk4: tests"
        run: xvfb-run --auto-servernum cargo test --manifest-path gdk4/Cargo.toml --all-features
      - name: "gdk4: build"
        run: cargo build --manifest-path gdk4/Cargo.toml --all-features
      # gtk4
      - name: "gtk4: tests"
        run: xvfb-run --auto-servernum cargo test --manifest-path gtk4/Cargo.toml --all-features
      - name: "gtk4: build"
        run: cargo build --manifest-path gtk4/Cargo.toml --all-features

      - uses: bcomnes/cleanup-xvfb@v1

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: rustup component add rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  regen_check:
    name: regen checker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - run: python3 generator.py --yes
      - run: git diff -R --exit-code

  checker:
    name: gtk-rs checker
    runs-on: ubuntu-latest
    strategy:
      matrix:
        crate:
          - gdk4
          - gsk4
          - gtk4
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: gtk-rs/checker
          ref: master
          path: checker
      - working-directory: checker
        run: cargo build --release
      - run: cargo run -- ../${{matrix.crate}}
        working-directory: checker
      - run: cargo run -- ../${{matrix.crate}}/sys
        working-directory: checker
      - run: ./check_init_asserts ../${{matrix.crate}}
        working-directory: checker
