name: docs

on:
  push:
    branches: [master]

jobs:
  build-deploy:
    runs-on: ubuntu-20.04
    name: build
    container:
      image: docker.io/bilelmoussaoui/gtk4
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - working-directory: gir
        run: cargo build --release
      - run: "./gir/target/release/gir -c ./gsk4/Gir.toml -d ./gir-files --doc-target-path docs.md -m doc"
      - run: "./gir/target/release/gir -c ./gdk4/Gir.toml -d ./gir-files --doc-target-path docs.md -m doc"
      - run: "./gir/target/release/gir -c ./gtk4/Gir.toml -d ./gir-files --doc-target-path docs.md -m doc"
      - run: "./gir/target/release/gir -c ./gdk4-x11/Gir.toml -d ./gir-files --doc-target-path docs.md -m doc"
      - run: "./gir/target/release/gir -c ./gdk4-wayland/Gir.toml -d ./gir-files --doc-target-path docs.md -m doc"
      - run: cargo install rustdoc-stripper
      - run: rustdoc-stripper -g -o ./gdk4/docs.md
      - run: rustdoc-stripper -g -o ./gsk4/docs.md
      - run: rustdoc-stripper -g -o ./gtk4/docs.md
      - run: rustdoc-stripper -g -o ./gdk4-x11/docs.md
      - run: rustdoc-stripper -g -o ./gdk4-wayland/docs.md
      - uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --workspace --no-deps

      - name: deploy
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./target/doc/
